# Keybinds (see docs/user/keybinds.md) --------------------------------------

[keybinds]
"Mod+Shift+O" = "cheatsheet-toggle"
"Mod+Q" = "window-close"
"Mod+O" = "overview-toggle"
"Mod+T" = "window-toggle-floating"
"Mod+Shift+T" = "window-focus-switch-floating"
"Mod+P" = "window-toggle-pinned"

#[scratchpad]
"Mod+5" = "window-toggle-scratchpad:terminal"
"Mod+Space" = "scratchpad-toggle:terminal"
"Mod+Shift+5" = "window-move-to-scratchpad:terminal"
"Mod+Ctrl+5" = "window-restore-from-scratchpad:terminal"

#[Moving around]
"Mod+Alt+1" = "workspace-switch:MAIN"
"Mod+Alt+2" = "workspace-switch:STORAGE"
"Mod+Alt+3" = "workspace-switch:CHAT"
"Mod+Alt+4" = "workspace-switch:HIDDEN"
"Mod+GRAVE" = "spawn:~/.config/umbriel/scripts/swapMonitors.sh"
"Mod+MouseMiddle" = "layout-scroll-drag"
"Mod+MouseForward" = "workspace-previous"
"Mod+MouseBack" = "workspace-next"
"Mod+Bracketright" = "window-focus-next"
"Mod+Bracketleft" = "window-focus-previous"
"Mod+Left" = "window-focus-left"
"Mod+Right" = "window-focus-right"
"Mod+Up" = "workspace-previous"
"Mod+Down" = "workspace-next"

#[Window Widths]
"Mod+1" = "window-set-primary-extent:0.25"
"Mod+2" = "window-set-primary-extent:0.50"
"Mod+3" = "window-set-primary-extent:0.333"
"Mod+4" = "window-set-primary-extent:0.75"
"Mod+WheelUp"   = "window-modify-primary-extent:0.05"
"Mod+WheelDown" = "window-modify-primary-extent:-0.05"

"Mod+F" = "window-toggle-fullscreen"
"Mod+Shift+R" = "window-cycle-primary-extent"
"Mod+R" = "window-toggle-maximize"

#[Applications]
"Mod+X" = "spawn:kitty"
"Mod+E" = "spawn:nautilus"
"Mod+B" = "spawn:helium-browser"
"Mod+D" = "spawn:vesktop"
"Mod+Z" = "spawn:zeditor"

#[Noctalia panels/menus]
"Mod" = "spawn:noctalia msg panel-toggle launcher"
"Mod+Escape" = "spawn:noctalia msg panel-toggle session"
"Mod+W" = "spawn:noctalia msg panel-toggle noctalia/wallhaven:browser"
"Mod+N" = "spawn:noctalia msg panel-toggle ahmedhossamdev/sticky-notes:panel"
"Mod+V" = "spawn:noctalia msg panel-toggle clipboard"
"Mod+S" = "spawn:noctalia msg screenshot-region"
"Mod+Shift+S" = "spawn:noctalia msg annotate"
"Mod+Comma" = "spawn:noctalia msg settings-toggle"
"Mod+Tab" = "spawn:noctalia msg window-switcher"

#[Volume/Audio]
"XF86AudioRaiseVolume" = "spawn:noctalia msg volume-up"
"XF86AudioLowerVolume" = "spawn:noctalia msg volume-down"
"XF86AudioMute"        = "spawn:noctalia msg volume-mute"
"XF86VoiceCommand"     = "spawn:noctalia msg mic-mute"
"XF86AudioPlay"        = "spawn:noctalia msg media toggle"
"XF86AudioNext"        = "spawn:noctalia msg media next"
"XF86AudioPrev"        = "spawn:noctalia msg media previous"
