[colors]
background = "#2b343bFF"
text_primary = "#f2f2f3FF"
text_muted = "#afb3b6FF"
accent_primary = "#8baac1FF"
accent_secondary = "#7f83b3FF"
warning = "#957fb3FF"
error = "#fd4663FF"
insert_hint = "#957fb380"
backdrop = "#212a30FF"

[colors.border]
focused = "#8baac1FF"
unfocused = "#212a30FF"
scratchpad_focused = "#957fb3FF"
scratchpad_unfocused = "#3c2a55FF"
outer = "#1a1f23FF"

[colors.overview]
background_tint = "#1a1f2388"
badge = "#8baac1FF"
workspace_background = "#1a1f23FF"
