[colors]
background = "#3b352bFF"
text_primary = "#f3f2f2FF"
text_muted = "#b6b4afFF"
accent_primary = "#d7b475FF"
accent_secondary = "#b9c76bFF"
warning = "#8dc270FF"
error = "#fd4663FF"
insert_hint = "#8dc27080"
backdrop = "#302b21FF"

[colors.border]
focused = "#d7b475FF"
unfocused = "#302b21FF"
scratchpad_focused = "#8dc270FF"
scratchpad_unfocused = "#375e21FF"
outer = "#23201aFF"

[colors.overview]
background_tint = "#23201a88"
badge = "#d7b475FF"
workspace_background = "#23201aFF"
