[colors]
background = "#3b3a2bFF"
text_primary = "#f3f3f2FF"
text_muted = "#b6b6afFF"
accent_primary = "#c1be8bFF"
accent_secondary = "#9bb181FF"
warning = "#85b082FF"
error = "#fd4663FF"
insert_hint = "#85b08280"
backdrop = "#302f21FF"

[colors.border]
focused = "#c1be8bFF"
unfocused = "#302f21FF"
scratchpad_focused = "#85b082FF"
scratchpad_unfocused = "#2f532cFF"
outer = "#23231aFF"

[colors.overview]
background_tint = "#23231a88"
badge = "#c1be8bFF"
workspace_background = "#23231aFF"
