# Outputs (see docs/user/outputs.md) ----------------------------------------

[output."DP-1"]
mode = "2560x1440@144"
position = [0,0]
vrr = "fullscreen"
tearing = true
workspaces = ["MAIN", "STORAGE"]
layout.scrolling.default_extent_fraction = 0.5

[output."DP-2"]
mode = "2560x1440@60"
position = [-1440, -520]
transform = "270"
vrr = "disabled"
tearing = false
workspaces = ["CHAT", "HIDDEN"]
workspace_axis = "horizontal"
layout.scrolling.default_extent_fraction = 0.5
