# Window rules (see docs/user/window-rules.md) ---------------------------

# Blur all windows
[[window_rule]]
blur = true
blur_optimized = false

# First Window opens all big man like
[[window_rule]]
match.is_alone = true
default_maximize = true

# When a window is not focused, let some light shine through
[[window_rule]]
match.is_focused = false
opacity = 0.92

# Open vesktop on DP-2
[[window_rule]]
match.app_id = "^vesktop$"
default_output = "DP-2"

# Do you play games?
[[window_rule]]
match.content_type = "game"
default_fullscreen = true

[[window_rule]]
match.xdg_tag = "^proton-game$"
default_fullscreen = true

[[window_rule]]
match.xdg_tag = "^steam$"
default_fullscreen = false
default_output = "DP-1"

# Noctalia gets floating
[[window_rule]]
match.app_id = "^dev.noctalia.Noctalia$"
default_floating = true
default_floating_size_px = { width = 1200, height = 800 }

[[window_rule]]
match.app_id = "^dev.noctalia.UmbrielSharePicker$"
default_floating = true
default_floating_size_px = { width = 1200, height = 800 }

# Floating file explorer
[[window_rule]]
match.app_id = "^org[.]gnome[.]Nautilus$"
default_floating = true
default_floating_size_px = { width = 1200, height = 800 }

# Need some PiP?
[[window_rule]]
match.title = "^(Picture-in-Picture|Picture in picture)$"
default_floating = true
default_maximize = false
default_position = { x = 20, y = 20, anchor = "bottom_right" }
